bases:
- ../base

resources:
- ingress.yaml

configMapGenerator:
- name: parameters
  literals:
  - PUBLIC_HOST=life-server.local
  - PUBLIC_URL=http://life-server.local
- name: life-server-env
  env: life-server.env
  behavior: merge

vars:
- name: PUBLIC_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldpath: data.PUBLIC_HOST
- name: PUBLIC_URL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldpath: data.PUBLIC_URL

patchesStrategicMerge:
- patch-solid-server-uri.yaml
